@extends('layouts.master')

@section('head')
    <link rel="stylesheet" href="/css/forms.css">
@stop

@section('content')
<!--
    *
    *
    Generated by register.blade.php
    *
    *
-->
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <center>
        <div class="wrapper">
            <h1>Register For An Account</h1>
            <p class="heading">To sign-up for a free basic account please provide us with some basic information using
                the contact form below. Please use valid credentials.</p>
                <form class="form" method="post" action='/register' accept-charset="UTF-8">
                    {!! csrf_field() !!}
                    <input type="text" class="name" name="name" placeholder="Name" value="{{old('name')}}">
                    <div>
                        <p class="name-help">Please enter your first and last name.</p>
                    </div>

                    <input type="email" class="email" name="email" placeholder="Email">
                    <div>
                        <p class="email-help">Please enter your current email address.</p>
                    </div>

                    <input type="password" name="password" placeholder="Password">
                    <div>
                        <p class="email-help">Please enter your password:</p>
                    </div>

                    <input type="password" name="password_confirmation" placeholder="Confirm Password">
                    <div>
                        <p class="email-help">Confirm your password.</p>
                    </div>

                    <input type="submit" class="submit" value="Register">
                </form>
            </div>
            <br><br>
            @if(count($errors) > 0)
                <ul class='errors'>
                    @foreach ($errors->all() as $error)
                        <li><span class='fa fa-exclamation-circle'></span> {{ $error }}</li>
                    @endforeach
                </ul>
            @endif
        </center>

<!-- End register.blade.php -->
@stop
