@extends('layouts.master')

@section('title')
myCloset - Add/Remove Tags
@stop

@section('head')
<style>
table, th, td {
    vertical-align:baseline;
    margin:auto;
}

th, td {
    padding-bottom: 10px;
    padding-right: 10px;
}

input[type=text] {
    width: 100px;

    font-size: 1em;
}

</style>
@stop

@section('content')
<!--
    *
    *
    Generated by edit.blade.php
    *
    *
-->

<div class="container">
    <div class="row">
        <div class="col-md-3"></div>

        <div class="col-md-6">
            <h1 class="h1" style="text-align: center;">Add/Remove Tags</h1>
            <div class="col-md-6">
                <img src="{{$item->src}}" class="img-thumbnail"/>
            </div>

            <div class="col-md-6">

                <table style="background:transparent;">
                    @foreach($item->tags as $tag)
                        <tr>
                            <td>
                                <button type="button" class="btn btn-success btn-sm btn-block">{{$tag->name}}</button>
                            </td>

                            <td>
                                <form action="/tags/unlink" method="post">
                                    {{ csrf_field() }}
                                    {!! Form::hidden('item_id', $item->id) !!}
                                    {!! Form::hidden('tag_id', $tag->id) !!}
                                <button type="submit" class="btn btn-danger btn-xs" value="X">X</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                    <td>
                        <div class="form-group">
                            <form action="/tags/link" method="post">
                                {{ csrf_field() }}
                                {!! Form::hidden('item_id', $item->id) !!}
                            <input class="form-control input-sm" type="text" placeholder="Tag" name="tag">
                        </div>
                    </td>
                    <td>
                        <button type="submit" class="btn btn-xs btn-primary">Add</button>
                    </form>
                    </td>
                </tr>
                </table>

            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>



            @if(count($errors) > 0)
                <ul class='errors'>
                    @foreach ($errors->all() as $error)
                        <li><span class='fa fa-exclamation-circle'></span> {{ $error }}</li>
                    @endforeach
                </ul>
            @endif

<!--
    *
    *
    END edit.blade.php
    *
    *
-->

@stop
