@extends('layouts.master')

@section('title')
myCloset - Add/Remove Tags
@stop

@section('head')
<style>

table, th, td {
    vertical-align:baseline;
    margin:auto;
}

th, td {
    padding-bottom: 5px;
    padding-right: 5px;
}

input[type=text] {
    width: 100px;

    font-size: 1em;
}

</style>
@stop

@section('content')
<!--
    *
    *
    Generated by edit.blade.php
    *
    *
-->

<div class="container">
    <div class="row">
        <div class="col-md-3"></div>

        <div class="col-md-6">
            <h1 class="h1" style="text-align: center;">Edit Item</h1>
            <div class="col-md-6">
                <img src="{{$item->src}}" class="img-thumbnail"/>
                <br>
                <form method="POST" action="/items/{{$item->id}}" role="form" accept-charset="UTF-8" enctype="multipart/form-data">
                    {!! csrf_field() !!}
                    {{ method_field('PATCH') }}
                <div class="form-group">
                    <label for="sel1">Worn:</label>
                    <select class="form-control" name="type" id="sel1" onchange='this.form.submit()'>
                        <option {{ ($item->type == "Top") ? "SELECTED" : ''}}>Top</option>
                        <option {{ ($item->type == "Bottom") ? "SELECTED" : ''}}>Bottom</option>
                        <option {{ ($item->type == "Shoe") ? "SELECTED" : ''}}>Shoes</option>
                        <option {{ ($item->type == "Accessory") ? "SELECTED" : ''}}>Accessory</option>
                    </select>
                </div>
            </form>

            </div>

            <div class="col-md-6">


                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title">Tags</h3>
                  </div>
                  <div class="panel-body">
                      <table style="background:transparent;">
                          @foreach($item->tags as $tag)
                              <tr>
                                  <td>
                                      <a href="/tags/{{$tag->id}}" class="btn btn-primary btn-sm btn-block">{{$tag->name}}</a>
                                  </td>

                                  <td>
                                      <form action="/tags/unlink" method="post">
                                          {{ csrf_field() }}
                                          {!! Form::hidden('item_id', $item->id) !!}
                                          {!! Form::hidden('tag_id', $tag->id) !!}
                                      <button type="submit" class="btn btn-danger btn-xs" value="X">X</button>
                                      </form>
                                  </td>
                              </tr>
                          @endforeach
                          <tr>
                          <td>
                              <div class="form-group">
                                  <form action="/tags/link" method="post">
                                      {{ csrf_field() }}
                                      {!! Form::hidden('item_id', $item->id) !!}
                                  <input class="form-control input-sm" type="text" autofocus placeholder="Tag" name="tag">
                              </div>
                          </td>
                          <td>
                              <button type="submit" class="btn btn-xs btn-default">Add</button>
                          </form>

                          </td>
                      </tr>
                      </table>
                  </div>
                </div>
                            @if(count($errors) > 0)
                                <ul class='errors'>
                                    @foreach ($errors->all() as $error)
                                        <li><span class='fa fa-exclamation-circle'></span> {{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>


<!--
    *
    *
    END edit.blade.php
    *
    *
-->

@stop
