<!DOCTYPE html>
    <!-- Autogenerated by master.blade.php -->
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>
        @yield('title','myCloset - a Wardrobe Manager')
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/custom.min.css">
    <link rel="stylesheet" href="/css/myCloset.css">

    <script src="/js/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/custom.js"></script>

    {{-- Yield any page specific CSS files or anything else you might want in the <head> --}}
    @yield('head')
</head>
<body>

@include('_partials.navbar')

<!-- padding below navbar -->
<div class="row">
    <div class="col-md-2 col-md-offset-5" style="padding: 10px;">
        @if(\Session::has('flash_message'))
          @include('_partials.flashMsg')
        @endif
    </div>
</div>
<!-- end padding below navbar -->


    @yield('content')

    {{-- Yield any page specific JS files or anything else you might want at the end of the body --}}
    @yield('body')

<!-- Autogenerated by master.blade.php -->
</body>
</html>
<!-- End master.blade.php -->
