
    <!-- Autogenerated by master.blade.php -->

<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>
        @yield('title','Dev myCloset')
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="/css/bootstrap.css" media="screen">
    <link rel="stylesheet" href="/css/custom.min.css">
    <link rel="stylesheet" href="/css/myCloset.css">

    <script src="/js/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/custom.js"></script>



    {{-- Yield any page specific CSS files or anything else you might want in the <head> --}}
    @yield('head')
</head>
<body>

<!--
    *
    *
    Navigation Bar
    *
    *
-->

<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">myCloset</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/upload">Add Item</a>
                    </li>
                    <li>
                        <a href="/items">List View</a>
                    </li>
                    <li>
                        <a href="/create">Create an Outfit</a>
                    </li>
                    <li>
                        <a href="/random">Random</a>
                    </li>
                </ul>

                @if(Auth::check())

                <ul class="nav navbar-nav navbar-right">
                <p class="navbar-text">Signed in as {{Auth::user()->name}}</p>
                <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                </ul>

                @else

                <ul class="nav navbar-nav navbar-right">
                  <li><a href="/register"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                  <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>

                @endif
        </div>
    </div>
</div>

<!-- padding below navbar -->
<div class="row">
    <div class="col-lg-12" style="padding: 25px;"></div>
</div>
    <!-- End master.blade.php -->

    @yield('content')

    {{-- Yield any page specific JS files or anything else you might want at the end of the body --}}
    @yield('body')

    @if(\Session::has('flash_message'))
      @include('messages.flash')
    @endif

    <!-- Autogenerated by master.blade.php -->
    <script src="/js/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/custom.js"></script>
</body>
</html>
    <!-- End master.blade.php -->
